require("malhar.plugin_config.colors")
require("malhar.plugin_config.telescope")
require("malhar.plugin_config.treesitter")
require("malhar.plugin_config.lualine")
require("malhar.plugin_config.nvim-tree")
require("malhar.plugin_config.lsp")
require("malhar.plugin_config.completions")
